from __future__ import annotations

from typing import Any, Callable, List, Optional, Tuple, Type, Union, overload

from ..model import Model
from ..types import DbReturnValue, Expression, QueryResolvable

class ConditionalClauseBuilder:
    def __init__(self, model_class: Type[Model]) -> None: ...

    # Where methods
    @overload
    def where(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def where(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    @overload
    def andWhere(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def andWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    @overload
    def orWhere(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def orWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    def whereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def andWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def orWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def whereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def andWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def orWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def whereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def andWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def orWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def whereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def andWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def orWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def whereExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def andWhereExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def orWhereExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def whereNotExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def andWhereNotExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def orWhereNotExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def whereLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def andWhereLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def orWhereLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def whereILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def andWhereILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def orWhereILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def whereNull(self, col: str) -> ConditionalClauseBuilder: ...
    def andWhereNull(self, col: str) -> ConditionalClauseBuilder: ...
    def orWhereNull(self, col: str) -> ConditionalClauseBuilder: ...
    def whereNotNull(self, col: str) -> ConditionalClauseBuilder: ...
    def andWhereNotNull(self, col: str) -> ConditionalClauseBuilder: ...
    def orWhereNotNull(self, col: str) -> ConditionalClauseBuilder: ...

    # Having methods
    @overload
    def having(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def having(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    @overload
    def andHaving(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def andHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    @overload
    def orHaving(
        self, column_or_callable: Callable[[ConditionalClauseBuilder], None]
    ) -> ConditionalClauseBuilder: ...
    @overload
    def orHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> ConditionalClauseBuilder: ...
    def havingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def andHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def orHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def havingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def andHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def orHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> ConditionalClauseBuilder: ...
    def havingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def andHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def orHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def havingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def andHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def orHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> ConditionalClauseBuilder: ...
    def havingExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def andHavingExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def orHavingExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def havingNotExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def andHavingNotExists(
        self, query: QueryResolvable
    ) -> ConditionalClauseBuilder: ...
    def orHavingNotExists(self, query: QueryResolvable) -> ConditionalClauseBuilder: ...
    def havingLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def andHavingLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def orHavingLike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def havingILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def andHavingILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def orHavingILike(self, col: str, pattern: str) -> ConditionalClauseBuilder: ...
    def havingNull(self, col: str) -> ConditionalClauseBuilder: ...
    def andHavingNull(self, col: str) -> ConditionalClauseBuilder: ...
    def orHavingNull(self, col: str) -> ConditionalClauseBuilder: ...
    def havingNotNull(self, col: str) -> ConditionalClauseBuilder: ...
    def andHavingNotNull(self, col: str) -> ConditionalClauseBuilder: ...
    def orHavingNotNull(self, col: str) -> ConditionalClauseBuilder: ...
