from typing import List, Optional, Tuple, Type

from ..compilers import Compiler
from ..model import Model
from ..types import ColumnReference

class GroupByClauseBuilder:
    def __init__(
        self, model_class: Type[Model], compiler: Optional[Compiler] = None
    ) -> None: ...
    def groupBy(self, *columns: ColumnReference) -> None: ...
    def set_mode(self, mode: str, columns: List[str]) -> None: ...
    def set_grouping_sets(self, sets: List[Tuple[str, ...]]) -> None: ...
