from __future__ import annotations

from typing import Any, Callable, List, Optional, Type, Union, overload

from ..builder import QueryBuilder
from ..compilers import Compiler
from ..model import Model

# The object a join lambda receives.
OnLambda = Callable[[OnClauseBuilder], Any]

class OnClauseBuilder:
    def __init__(self, compiler: Optional[Compiler] = None) -> None: ...
    def on(
        self, col1: str, op: str, col2: Union[str, QueryBuilder[Any]]
    ) -> OnClauseBuilder: ...
    def andOn(
        self, col1: str, op: str, col2: Union[str, QueryBuilder[Any]]
    ) -> OnClauseBuilder: ...
    def orOn(
        self, col1: str, op: str, col2: Union[str, QueryBuilder[Any]]
    ) -> OnClauseBuilder: ...
    def __str__(self) -> str: ...

class JoinClauseBuilder:
    def __init__(
        self, model_class: Type[Model], compiler: Optional[Compiler] = None
    ) -> None: ...
    def __str__(self) -> str: ...

    # Raw form: an ON condition, a lambda, or a USING list.
    @overload
    def join(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def join(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def join(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder[Any]], /
    ) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...

    # Relation form: the ON condition comes from relationMappings.
    def joinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def innerJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def leftJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def leftOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def rightJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def rightOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def fullJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def fullOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def crossJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
