from __future__ import annotations

from typing import Callable, Dict, List, Optional, Type, Union, overload

from ..compilers import Compiler
from ..model import Model
from ..types import AnyQuery

# The object a join lambda receives. Whatever the lambda returns is
# discarded, so the return type is left open.
OnLambda = Callable[[OnClauseBuilder], object]

class OnClauseBuilder:
    def __init__(self, compiler: Optional[Compiler] = None) -> None: ...
    def on(self, col1: str, op: str, col2: Union[str, AnyQuery]) -> OnClauseBuilder: ...
    def andOn(
        self, col1: str, op: str, col2: Union[str, AnyQuery]
    ) -> OnClauseBuilder: ...
    def orOn(
        self, col1: str, op: str, col2: Union[str, AnyQuery]
    ) -> OnClauseBuilder: ...
    def __str__(self) -> str: ...

class JoinClauseBuilder:
    _JOIN_METHOD_MAP: Dict[str, str]
    def __init__(
        self, model_class: Type[Model], compiler: Optional[Compiler] = None
    ) -> None: ...
    def __str__(self) -> str: ...

    # Raw form: an ON condition, a lambda, or a USING list.
    @overload
    def join(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def join(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def join(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def innerJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def leftJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def leftOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def rightJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def rightOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def fullJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def fullOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(self, table: str, on: OnLambda, /) -> JoinClauseBuilder: ...
    @overload
    def crossJoin(self, table: str, /, *, using: List[str]) -> JoinClauseBuilder: ...

    # Relation form: the ON condition comes from relationMappings.
    def joinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def innerJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def leftJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def leftOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def rightJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def rightOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def fullJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def fullOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
    def crossJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> JoinClauseBuilder: ...
