# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        pass_filenames: false
        always_run: true
        args: ["-p", "sustained", "--strict", "--check-untyped-defs"]

  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: bash -c "PYTHONPATH=src python3 -m unittest discover -s tests"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
