"""
Tests for typed column definitions and model-driven DDL.
"""

import sqlite3
import unittest

from sustained import DialectError, Model
from sustained.dialects import Dialects
from sustained.schema import (
    BigInteger,
    Binary,
    Boolean,
    ColumnDef,
    Date,
    Float,
    Integer,
    Json,
    Numeric,
    String,
    Text,
    Timestamp,
)
from sustained.types import Expression


class DdlUser(Model):
    tableName = "users"
    tableColumns = {
        "id": Integer(primary_key=True, autoincrement=True),
        "email": String(120, unique=True, nullable=False),
        "bio": Text(),
        "active": Boolean(default=True),
        "balance": Numeric(12, 2, default=0),
        "meta": Json(),
        "created_at": Timestamp(default=Expression("CURRENT_TIMESTAMP")),
    }


class TestCreateTableSql(unittest.TestCase):
    def tearDown(self):
        DdlUser.set_dialect(Dialects.DEFAULT)

    def test_default_dialect(self):
        sql = DdlUser.create_table_sql()
        self.assertEqual(
            sql,
            "CREATE TABLE users (id INTEGER PRIMARY KEY, "
            "email VARCHAR(120) NOT NULL UNIQUE, bio TEXT, "
            "active BOOLEAN DEFAULT TRUE, balance NUMERIC(12, 2) DEFAULT 0, "
            "meta JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
        )

    def test_postgres_types_and_identity(self):
        DdlUser.set_dialect(Dialects.POSTGRES)
        sql = DdlUser.create_table_sql(if_not_exists=True)
        self.assertIn('CREATE TABLE IF NOT EXISTS "users"', sql)
        self.assertIn('"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql)
        self.assertIn('"meta" JSONB', sql)

    def test_mssql_types_and_identity(self):
        DdlUser.set_dialect(Dialects.MSSQL)
        sql = DdlUser.create_table_sql()
        self.assertIn("[id] INTEGER IDENTITY(1,1) PRIMARY KEY", sql)
        self.assertIn("[active] BIT DEFAULT 1", sql)
        self.assertIn("[bio] NVARCHAR(MAX)", sql)
        self.assertIn("[created_at] DATETIME2", sql)

    def test_duckdb_identity_raises(self):
        DdlUser.set_dialect(Dialects.DUCKDB)
        with self.assertRaises(DialectError):
            DdlUser.create_table_sql()

    def test_columns_derived_from_table_columns(self):
        self.assertEqual(
            DdlUser.columns,
            ("id", "email", "bio", "active", "balance", "meta", "created_at"),
        )
        with self.assertRaises(AttributeError):
            DdlUser.c.nope

    def test_drop_table_sql(self):
        self.assertEqual(DdlUser.drop_table_sql(), "DROP TABLE IF EXISTS users")
        self.assertEqual(DdlUser.drop_table_sql(if_exists=False), "DROP TABLE users")


class TestConstraints(unittest.TestCase):
    def test_composite_primary_key_and_references(self):
        class Link(Model):
            tableName = "links"
            tableColumns = {
                "a": Integer(primary_key=True, references="users.id"),
                "b": BigInteger(primary_key=True),
            }

        sql = Link.create_table_sql()
        self.assertIn("a INTEGER NOT NULL REFERENCES users (id)", sql)
        self.assertIn("PRIMARY KEY (a, b)", sql)

    def test_composite_pk_with_autoincrement_rejected(self):
        class Bad(Model):
            tableName = "bad"
            tableColumns = {
                "a": Integer(primary_key=True, autoincrement=True),
                "b": Integer(primary_key=True),
            }

        with self.assertRaises(ValueError):
            Bad.create_table_sql()

    def test_autoincrement_validation(self):
        with self.assertRaises(ValueError):
            Text(primary_key=True, autoincrement=True)
        with self.assertRaises(ValueError):
            Integer(autoincrement=True)

    def test_bad_reference_format(self):
        with self.assertRaises(ValueError):
            Integer(references="users")

    def test_unknown_type_rejected(self):
        class Weird(Model):
            tableName = "weird"
            tableColumns = {"x": ColumnDef("GEOMETRY")}

        with self.assertRaises(ValueError):
            Weird.create_table_sql()

    def test_no_columns_rejected(self):
        class Empty(Model):
            tableName = "empty_tbl"

        with self.assertRaises(ValueError):
            Empty.create_table_sql()

    def test_binary_type_per_dialect(self):
        class Blobby(Model):
            tableName = "blobby"
            tableColumns = {"data": Binary()}

        try:
            self.assertIn("data BLOB", Blobby.create_table_sql())
            Blobby.set_dialect(Dialects.POSTGRES)
            self.assertIn('"data" BYTEA', Blobby.create_table_sql())
            Blobby.set_dialect(Dialects.MSSQL)
            self.assertIn("[data] VARBINARY(MAX)", Blobby.create_table_sql())
            Blobby.set_dialect(Dialects.PRESTO)
            self.assertIn('"data" VARBINARY', Blobby.create_table_sql())
            Blobby.set_dialect(Dialects.ATHENA)
            self.assertIn("BINARY", Blobby.create_table_sql())
        finally:
            Blobby.set_dialect(Dialects.DEFAULT)

    def test_float_and_date_types(self):
        class Mixed(Model):
            tableName = "mixed"
            tableColumns = {"f": Float(), "d": Date()}

        sql = Mixed.create_table_sql()
        self.assertIn("f DOUBLE PRECISION", sql)
        self.assertIn("d DATE", sql)


class TestLiveDdl(unittest.TestCase):
    def test_create_insert_drop_on_sqlite(self):
        conn = sqlite3.connect(":memory:")
        DdlUser.create_table(conn)
        DdlUser.bind(conn)
        try:
            DdlUser.query().insert(
                {"email": "a@x", "bio": "hi", "active": True, "balance": 1.5}
            ).run()
            row = DdlUser.query().first()
            self.assertEqual(row.email, "a@x")
            self.assertEqual(row.id, 1)
            DdlUser.drop_table(conn)
        finally:
            DdlUser.unbind()
            conn.close()

    def test_binary_round_trip_on_sqlite(self):
        class Blob(Model):
            tableName = "blobs"
            tableColumns = {"id": Integer(primary_key=True), "data": Binary()}

        conn = sqlite3.connect(":memory:")
        Blob.create_table(conn)
        Blob.bind(conn)
        try:
            Blob.query().insert({"id": 1, "data": b"\x00\xff"}).run()
            self.assertEqual(Blob.query().first().data, b"\x00\xff")
        finally:
            Blob.unbind()
            conn.close()

    def test_create_table_without_connection_raises(self):
        with self.assertRaises(RuntimeError):
            DdlUser.create_table()


class RecordingCursor:
    """A cursor that keeps every statement it runs."""

    description = None
    rowcount = -1

    def __init__(self, statements):
        self._statements = statements

    def execute(self, sql, params=None):
        self._statements.append(sql)

    def fetchall(self):
        return []

    def close(self):
        pass


class RecordingConnection:
    """A connection that counts commits and rollbacks."""

    def __init__(self):
        self.statements = []
        self.commits = 0
        self.rollbacks = 0

    def cursor(self):
        return RecordingCursor(self.statements)

    def commit(self):
        self.commits += 1

    def rollback(self):
        self.rollbacks += 1


class CommitlessConnection:
    """A connection with no commit method, such as an autocommit driver."""

    def __init__(self):
        self.statements = []

    def cursor(self):
        return RecordingCursor(self.statements)


class TestDdlCommits(unittest.TestCase):
    def test_create_table_commits(self):
        conn = RecordingConnection()
        DdlUser.create_table(conn)
        self.assertEqual(conn.commits, 1)

    def test_drop_table_commits(self):
        conn = RecordingConnection()
        DdlUser.drop_table(conn)
        self.assertEqual(conn.commits, 1)

    def test_create_table_inside_transaction_does_not_commit(self):
        conn = RecordingConnection()
        with DdlUser.transaction(conn):
            DdlUser.create_table(conn)
            self.assertEqual(conn.commits, 0)
        # The transaction block owns the single commit.
        self.assertEqual(conn.commits, 1)

    def test_drop_table_inside_transaction_does_not_commit(self):
        conn = RecordingConnection()
        with DdlUser.transaction(conn):
            DdlUser.drop_table(conn)
            self.assertEqual(conn.commits, 0)
        self.assertEqual(conn.commits, 1)

    def test_create_table_without_commit_method(self):
        conn = CommitlessConnection()
        DdlUser.create_table(conn)
        self.assertTrue(conn.statements)


if __name__ == "__main__":
    unittest.main()
