from __future__ import annotations

from typing import (
    Any,
    Callable,
    Dict,
    Generic,
    List,
    Mapping,
    Optional,
    Tuple,
    Type,
    TypeVar,
    Union,
    overload,
)

from .aio import AsyncAdapter
from .builders import (
    GroupByClauseBuilder,
    HavingClauseBuilder,
    OrderByClauseBuilder,
    SelectClauseBuilder,
    WhereClauseBuilder,
)
from .builders.join_builder import OnLambda
from .dialects import Dialects
from .expressions import (
    AggregateExpression,
    CaseExpression,
    Column,
    Predicate,
    WindowExpression,
)
from .model import Model
from .rendering import RenderContext
from .types import (
    AnyQuery,
    Binding,
    CaseResult,
    DbReturnValue,
    Expression,
    QueryResolvable,
    RowValue,
    Selectable,
    SqlValue,
    WriteResult,
)

TModel = TypeVar("TModel", bound=Model)
TQuery = TypeVar("TQuery")

class _Clauses(Generic[TQuery]):
    """
    The methods a SELECT and a write statement both accept. TQuery is the
    builder the chain returns, so a WHERE on a DELETE stays a DELETE.
    """

    _model_class: Type[Model]
    _stmt_type: str
    _insert_rows: List[Dict[str, SqlValue]]
    _returning_columns: List[str]
    _eager_relations: List[str]
    def __str__(self) -> str: ...
    def _render_sql(self, ctx: RenderContext, include_ctes: bool = True) -> str: ...
    def to_sql(self) -> Tuple[str, Tuple[SqlValue, ...]]: ...
    def clone(self) -> TQuery: ...
    # Where methods
    @overload
    def where(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> TQuery: ...
    @overload
    def where(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> TQuery: ...
    @overload
    def andWhere(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> TQuery: ...
    @overload
    def andWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> TQuery: ...
    @overload
    def orWhere(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> TQuery: ...
    @overload
    def orWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> TQuery: ...
    def whereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def andWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def orWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def whereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def andWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def orWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> TQuery: ...
    def whereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def andWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def orWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def whereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def andWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def orWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> TQuery: ...
    def whereExists(self, query: QueryResolvable) -> TQuery: ...
    def andWhereExists(self, query: QueryResolvable) -> TQuery: ...
    def orWhereExists(self, query: QueryResolvable) -> TQuery: ...
    def whereNotExists(self, query: QueryResolvable) -> TQuery: ...
    def andWhereNotExists(self, query: QueryResolvable) -> TQuery: ...
    def orWhereNotExists(self, query: QueryResolvable) -> TQuery: ...
    def whereLike(self, col: str, pattern: str) -> TQuery: ...
    def andWhereLike(self, col: str, pattern: str) -> TQuery: ...
    def orWhereLike(self, col: str, pattern: str) -> TQuery: ...
    def whereILike(self, col: str, pattern: str) -> TQuery: ...
    def andWhereILike(self, col: str, pattern: str) -> TQuery: ...
    def orWhereILike(self, col: str, pattern: str) -> TQuery: ...
    def whereNull(self, col: str) -> TQuery: ...
    def andWhereNull(self, col: str) -> TQuery: ...
    def orWhereNull(self, col: str) -> TQuery: ...
    def whereNotNull(self, col: str) -> TQuery: ...
    def andWhereNotNull(self, col: str) -> TQuery: ...
    def orWhereNotNull(self, col: str) -> TQuery: ...

    # Raw predicates. The fragment marks each value with ?, and the values
    # travel as parameters. Both arguments are positional.
    def whereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> TQuery: ...
    def andWhereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> TQuery: ...
    def orWhereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> TQuery: ...

class QueryBuilder(_Clauses["QueryBuilder[TModel]"], Generic[TModel]):
    """
    A SELECT statement for one model. Model.query() hands you one already
    bound to that model, so run() gives back that model's instances.
    """

    def __init__(
        self, model_class: Type[TModel], dialect: Optional[Dialects] = None
    ) -> None: ...
    def distinct(self) -> QueryBuilder[TModel]: ...
    def select(self, *columns: Selectable) -> QueryBuilder[TModel]: ...
    def count(
        self, column: str = "*", alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def sum(self, column: str, alias: Optional[str] = None) -> QueryBuilder[TModel]: ...
    def avg(self, column: str, alias: Optional[str] = None) -> QueryBuilder[TModel]: ...
    def min(self, column: str, alias: Optional[str] = None) -> QueryBuilder[TModel]: ...
    def max(self, column: str, alias: Optional[str] = None) -> QueryBuilder[TModel]: ...
    def select_func(
        self, function_name: str, *args: SqlValue, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def lower(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def upper(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def coalesce(
        self, *args: SqlValue, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def concat(
        self, *args: SqlValue, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def getdate(
        self, *args: SqlValue, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def now(
        self, *args: SqlValue, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def substring(
        self,
        column: str,
        start: int,
        length: Optional[int] = None,
        alias: Optional[str] = None,
    ) -> QueryBuilder[TModel]: ...
    def trim(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def length(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def round(
        self, column: str, decimals: int = 0, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def abs(self, column: str, alias: Optional[str] = None) -> QueryBuilder[TModel]: ...
    def ceiling(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def floor(
        self, column: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def mod(
        self, column: str, divisor: int, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def select_window(
        self,
        function_name: str,
        alias: str,
        partition_by: Optional[List[str]] = None,
        order_by: Optional[List[str]] = None,
        args: Optional[List[SqlValue]] = None,
        frame: Optional[str] = None,
    ) -> QueryBuilder[TModel]: ...
    def select_case(
        self,
        alias: str,
        else_result: CaseResult,
        when_clauses: List[Tuple[str, CaseResult]],
    ) -> QueryBuilder[TModel]: ...
    def from_(
        self, table: Union[AnyQuery, str], alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def with_(
        self,
        table_alias: str,
        subquery: AnyQuery,
        recursive: bool = False,
    ) -> QueryBuilder[TModel]: ...
    def groupBy(self, *columns: str) -> QueryBuilder[TModel]: ...
    @staticmethod
    def raw(sql: str) -> Expression: ...
    def limit(self, value: int) -> QueryBuilder[TModel]: ...
    def top(self, value: int) -> QueryBuilder[TModel]: ...
    def union(self, *queries: AnyQuery, all: bool = False) -> QueryBuilder[TModel]: ...
    def unionAll(self, *queries: AnyQuery) -> QueryBuilder[TModel]: ...
    def intersect(self, *queries: AnyQuery) -> QueryBuilder[TModel]: ...
    def except_(self, *queries: AnyQuery) -> QueryBuilder[TModel]: ...
    def distinctOn(self, *columns: str) -> QueryBuilder[TModel]: ...
    def groupByRollup(self, *columns: str) -> QueryBuilder[TModel]: ...
    def groupByCube(self, *columns: str) -> QueryBuilder[TModel]: ...
    def groupByGroupingSets(self, *sets: Tuple[str, ...]) -> QueryBuilder[TModel]: ...
    def qualify(self, condition: Union[str, Predicate]) -> QueryBuilder[TModel]: ...
    def for_update(
        self, skip_locked: bool = False, nowait: bool = False
    ) -> QueryBuilder[TModel]: ...
    def total(self, connection: Optional[Binding] = None) -> int: ...
    def cursor_page(
        self, column: str, page_size: int, after: Optional[SqlValue] = None
    ) -> QueryBuilder[TModel]: ...
    def explain(
        self, connection: Optional[Binding] = None, analyze: bool = False
    ) -> List[Tuple[RowValue, ...]]: ...
    def offset(self, value: int) -> QueryBuilder[TModel]: ...
    def page(self, page: int, page_size: int) -> QueryBuilder[TModel]: ...
    def insert(
        self, values: Union[Mapping[str, SqlValue], List[Mapping[str, SqlValue]]]
    ) -> WriteBuilder[TModel]: ...
    def insert_from(
        self, columns: Optional[List[str]], query: AnyQuery
    ) -> WriteBuilder[TModel]: ...
    def create_table_as(
        self, table_name: str, temporary: bool = False
    ) -> WriteBuilder[TModel]: ...
    def update(self, values: Mapping[str, SqlValue]) -> WriteBuilder[TModel]: ...
    def delete(self) -> WriteBuilder[TModel]: ...
    def withGraphFetched(self, *relation_names: str) -> QueryBuilder[TModel]: ...
    def to_dicts(
        self, connection: Optional[Binding] = None
    ) -> List[Dict[str, RowValue]]: ...
    # pandas and pyarrow are optional installs. Naming their types here
    # would make Sustained fail to type check for anyone who skips them,
    # so the DataFrame and Table types are left open.
    def to_df(self, connection: Optional[Binding] = None) -> Any: ...
    def to_arrow(self, connection: Optional[Binding] = None) -> Any: ...
    def run(self, connection: Optional[Binding] = None) -> List[TModel]: ...
    async def arun(self, adapter: Optional[AsyncAdapter] = None) -> List[TModel]: ...
    async def afirst(
        self, adapter: Optional[AsyncAdapter] = None
    ) -> Optional[TModel]: ...
    async def ato_dicts(
        self, adapter: Optional[AsyncAdapter] = None
    ) -> List[Dict[str, RowValue]]: ...
    def first(self, connection: Optional[Binding] = None) -> Optional[TModel]: ...

    # Join methods, raw form: an ON condition, a lambda, or a USING list.
    @overload
    def join(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def join(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def join(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...
    @overload
    def innerJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def innerJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def innerJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...
    @overload
    def leftJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def leftJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def leftJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...
    @overload
    def leftOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def leftOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def leftOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> QueryBuilder[TModel]: ...
    @overload
    def rightJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def rightJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def rightJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...
    @overload
    def rightOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def rightOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def rightOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> QueryBuilder[TModel]: ...
    @overload
    def fullJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def fullJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def fullJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...
    @overload
    def fullOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def fullOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def fullOuterJoin(
        self, table: str, /, *, using: List[str]
    ) -> QueryBuilder[TModel]: ...
    @overload
    def crossJoin(
        self, table: str, col1: str, op: str, col2: Union[str, AnyQuery], /
    ) -> QueryBuilder[TModel]: ...
    @overload
    def crossJoin(self, table: str, on: OnLambda, /) -> QueryBuilder[TModel]: ...
    @overload
    def crossJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder[TModel]: ...

    # Relation form: the ON condition comes from relationMappings.
    def joinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def innerJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def leftJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def leftOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def rightJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def rightOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def fullJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def fullOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...
    def crossJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder[TModel]: ...

    # Order By methods
    def orderBy(self, column: str, direction: str = "ASC") -> QueryBuilder[TModel]: ...

    # Having methods
    @overload
    def having(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder[TModel]: ...
    @overload
    def having(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder[TModel]: ...
    @overload
    def andHaving(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder[TModel]: ...
    @overload
    def andHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder[TModel]: ...
    @overload
    def orHaving(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder[TModel]: ...
    @overload
    def orHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder[TModel]: ...
    def havingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def andHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def orHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def havingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def andHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def orHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder[TModel]: ...
    def havingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def andHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def orHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def havingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def andHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def orHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder[TModel]: ...
    def havingExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def andHavingExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def orHavingExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def havingNotExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def andHavingNotExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def orHavingNotExists(self, query: QueryResolvable) -> QueryBuilder[TModel]: ...
    def havingLike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def andHavingLike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def orHavingLike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def havingILike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def andHavingILike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def orHavingILike(self, col: str, pattern: str) -> QueryBuilder[TModel]: ...
    def havingNull(self, col: str) -> QueryBuilder[TModel]: ...
    def andHavingNull(self, col: str) -> QueryBuilder[TModel]: ...
    def orHavingNull(self, col: str) -> QueryBuilder[TModel]: ...
    def havingNotNull(self, col: str) -> QueryBuilder[TModel]: ...
    def andHavingNotNull(self, col: str) -> QueryBuilder[TModel]: ...
    def orHavingNotNull(self, col: str) -> QueryBuilder[TModel]: ...
    def havingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder[TModel]: ...
    def andHavingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder[TModel]: ...
    def orHavingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder[TModel]: ...

class WriteBuilder(_Clauses["WriteBuilder[TModel]"], Generic[TModel]):
    """
    An INSERT, UPDATE, DELETE, or CREATE TABLE AS statement. run() returns
    the affected row count, or the RETURNING rows as dicts. At runtime this
    is the same class as QueryBuilder; the split is how the type checker
    tells a write apart from a read.
    """

    def returning(self, *columns: str) -> WriteBuilder[TModel]: ...
    def onConflict(self, *columns: str) -> WriteBuilder[TModel]: ...
    def merge(self, columns: Optional[List[str]] = None) -> WriteBuilder[TModel]: ...
    def ignore(self) -> WriteBuilder[TModel]: ...
    def run(self, connection: Optional[Binding] = None) -> WriteResult: ...
    async def arun(self, adapter: Optional[AsyncAdapter] = None) -> WriteResult: ...
