from __future__ import annotations

from typing import (
    Any,
    Callable,
    Dict,
    List,
    Optional,
    Tuple,
    Type,
    Union,
    overload,
)

from .builders import (
    GroupByClauseBuilder,
    HavingClauseBuilder,
    OrderByClauseBuilder,
    SelectClauseBuilder,
    WhereClauseBuilder,
)
from .builders.join_builder import OnLambda
from .dialects import Dialects
from .expressions import (
    AggregateExpression,
    CaseExpression,
    Column,
    Predicate,
    WindowExpression,
)
from .model import Model
from .rendering import RenderContext
from .types import CaseResult, DbReturnValue, Expression, QueryResolvable, Selectable

class QueryBuilder:
    _model_class: Type[Model]
    _stmt_type: str
    _insert_rows: List[Dict[str, Any]]
    _returning_columns: List[str]
    _eager_relations: List[str]
    def __init__(
        self, model_class: Type[Model], dialect: Optional[Dialects] = None
    ) -> None: ...
    def distinct(self) -> QueryBuilder: ...
    def select(self, *columns: Selectable) -> QueryBuilder: ...
    def count(self, column: str = "*", alias: Optional[str] = None) -> QueryBuilder: ...
    def sum(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def avg(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def min(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def max(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def select_func(
        self, function_name: str, *args: Any, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def lower(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def upper(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def coalesce(self, *args: Any, alias: Optional[str] = None) -> QueryBuilder: ...
    def concat(self, *args: Any, alias: Optional[str] = None) -> QueryBuilder: ...
    def getdate(self, *args: Any, alias: Optional[str] = None) -> QueryBuilder: ...
    def now(self, *args: Any, alias: Optional[str] = None) -> QueryBuilder: ...
    def substring(
        self,
        column: str,
        start: int,
        length: Optional[int] = None,
        alias: Optional[str] = None,
    ) -> QueryBuilder: ...
    def trim(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def length(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def round(
        self, column: str, decimals: int = 0, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def abs(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def ceiling(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def floor(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def mod(
        self, column: str, divisor: int, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def select_window(
        self,
        function_name: str,
        alias: str,
        partition_by: Optional[List[str]] = None,
        order_by: Optional[List[str]] = None,
        args: Optional[List[Any]] = None,
        frame: Optional[str] = None,
    ) -> QueryBuilder: ...
    def select_case(
        self,
        alias: str,
        else_result: CaseResult,
        when_clauses: List[Tuple[str, CaseResult]],
    ) -> QueryBuilder: ...
    def from_(
        self, table: Union[QueryBuilder, str], alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def with_(
        self,
        table_alias: str,
        subquery: QueryBuilder,
        recursive: bool = False,
    ) -> QueryBuilder: ...
    def groupBy(self, *columns: str) -> QueryBuilder: ...
    @staticmethod
    def raw(sql: str) -> Expression: ...
    def __str__(self) -> str: ...
    def _render_sql(self, ctx: RenderContext, include_ctes: bool = True) -> str: ...
    def to_sql(self) -> Tuple[str, Tuple[DbReturnValue, ...]]: ...
    def limit(self, value: int) -> QueryBuilder: ...
    def top(self, value: int) -> QueryBuilder: ...
    def union(self, *queries: QueryBuilder, all: bool = False) -> QueryBuilder: ...
    def unionAll(self, *queries: QueryBuilder) -> QueryBuilder: ...
    def intersect(self, *queries: QueryBuilder) -> QueryBuilder: ...
    def except_(self, *queries: QueryBuilder) -> QueryBuilder: ...
    def distinctOn(self, *columns: str) -> QueryBuilder: ...
    def groupByRollup(self, *columns: str) -> QueryBuilder: ...
    def groupByCube(self, *columns: str) -> QueryBuilder: ...
    def groupByGroupingSets(self, *sets: Tuple[str, ...]) -> QueryBuilder: ...
    def qualify(self, condition: Union[str, Predicate]) -> QueryBuilder: ...
    def for_update(
        self, skip_locked: bool = False, nowait: bool = False
    ) -> QueryBuilder: ...
    def total(self, connection: Optional[Any] = None) -> int: ...
    def cursor_page(
        self, column: str, page_size: int, after: Optional[Any] = None
    ) -> QueryBuilder: ...
    def explain(
        self, connection: Optional[Any] = None, analyze: bool = False
    ) -> List[Tuple[Any, ...]]: ...
    def offset(self, value: int) -> QueryBuilder: ...
    def page(self, page: int, page_size: int) -> QueryBuilder: ...
    def clone(self) -> QueryBuilder: ...
    def insert(
        self, values: Union[Dict[str, Any], List[Dict[str, Any]]]
    ) -> QueryBuilder: ...
    def insert_from(
        self, columns: Optional[List[str]], query: QueryBuilder
    ) -> QueryBuilder: ...
    def create_table_as(
        self, table_name: str, temporary: bool = False
    ) -> QueryBuilder: ...
    def onConflict(self, *columns: str) -> QueryBuilder: ...
    def merge(self, columns: Optional[List[str]] = None) -> QueryBuilder: ...
    def ignore(self) -> QueryBuilder: ...
    def update(self, values: Dict[str, Any]) -> QueryBuilder: ...
    def delete(self) -> QueryBuilder: ...
    def returning(self, *columns: str) -> QueryBuilder: ...
    def withGraphFetched(self, *relation_names: str) -> QueryBuilder: ...
    def to_dicts(self, connection: Optional[Any] = None) -> List[Dict[str, Any]]: ...
    def to_df(self, connection: Optional[Any] = None) -> Any: ...
    def to_arrow(self, connection: Optional[Any] = None) -> Any: ...
    def run(self, connection: Optional[Any] = None) -> Any: ...
    async def arun(self, adapter: Optional[Any] = None) -> Any: ...
    async def afirst(self, adapter: Optional[Any] = None) -> Optional[Model]: ...
    async def ato_dicts(
        self, adapter: Optional[Any] = None
    ) -> List[Dict[str, Any]]: ...
    def first(self, connection: Optional[Any] = None) -> Optional[Model]: ...

    # Join methods, raw form: an ON condition, a lambda, or a USING list.
    @overload
    def join(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def join(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def join(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def innerJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def innerJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def innerJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def leftJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def leftJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def leftJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def leftOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def leftOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def leftOuterJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def rightJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def rightJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def rightJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def rightOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def rightOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def rightOuterJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def fullJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def fullJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def fullJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def fullOuterJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def fullOuterJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def fullOuterJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...
    @overload
    def crossJoin(
        self, table: str, col1: str, op: str, col2: Union[str, QueryBuilder], /
    ) -> QueryBuilder: ...
    @overload
    def crossJoin(self, table: str, on: OnLambda, /) -> QueryBuilder: ...
    @overload
    def crossJoin(self, table: str, /, *, using: List[str]) -> QueryBuilder: ...

    # Relation form: the ON condition comes from relationMappings.
    def joinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def innerJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def leftJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def leftOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def rightJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def rightOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def fullJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def fullOuterJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def crossJoinRelated(
        self, relation_name: str, alias: Optional[str] = None
    ) -> QueryBuilder: ...

    # Order By methods
    def orderBy(self, column: str, direction: str = "ASC") -> QueryBuilder: ...

    # Where methods
    @overload
    def where(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def where(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    @overload
    def andWhere(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def andWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    @overload
    def orWhere(
        self,
        column_or_callable: Union[Callable[[WhereClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def orWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    def whereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def whereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def whereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def whereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def whereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andWhereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orWhereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def whereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andWhereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orWhereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def whereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andWhereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orWhereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def whereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andWhereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orWhereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def whereNull(self, col: str) -> QueryBuilder: ...
    def andWhereNull(self, col: str) -> QueryBuilder: ...
    def orWhereNull(self, col: str) -> QueryBuilder: ...
    def whereNotNull(self, col: str) -> QueryBuilder: ...
    def andWhereNotNull(self, col: str) -> QueryBuilder: ...
    def orWhereNotNull(self, col: str) -> QueryBuilder: ...

    # Raw predicates. The fragment marks each value with ?, and the values
    # travel as parameters. Both arguments are positional.
    def whereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...
    def andWhereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...
    def orWhereRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...

    # Having methods
    @overload
    def having(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def having(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    @overload
    def andHaving(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def andHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    @overload
    def orHaving(
        self,
        column_or_callable: Union[Callable[[HavingClauseBuilder], None], Predicate],
    ) -> QueryBuilder: ...
    @overload
    def orHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Optional[Union[Expression, DbReturnValue]],
    ) -> QueryBuilder: ...
    def havingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def havingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def havingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def havingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def havingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andHavingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orHavingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def havingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andHavingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orHavingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def havingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andHavingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orHavingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def havingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andHavingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orHavingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def havingNull(self, col: str) -> QueryBuilder: ...
    def andHavingNull(self, col: str) -> QueryBuilder: ...
    def orHavingNull(self, col: str) -> QueryBuilder: ...
    def havingNotNull(self, col: str) -> QueryBuilder: ...
    def andHavingNotNull(self, col: str) -> QueryBuilder: ...
    def orHavingNotNull(self, col: str) -> QueryBuilder: ...
    def havingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...
    def andHavingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...
    def orHavingRaw(
        self, sql: str, params: Optional[List[DbReturnValue]] = None, /
    ) -> QueryBuilder: ...
