from __future__ import annotations

from typing import (
    Any,
    Callable,
    Dict,
    List,
    Optional,
    Tuple,
    Type,
    Union,
    overload,
)

from .builders import (
    GroupByClauseBuilder,
    HavingClauseBuilder,
    JoinClauseBuilder,
    OrderByClauseBuilder,
    SelectClauseBuilder,
    WhereClauseBuilder,
)
from .expressions import (
    AggregateExpression,
    CaseExpression,
    Column,
    WindowExpression,
)
from .model import Model
from .types import CaseResult, DbReturnValue, Expression, QueryResolvable, Selectable

class QueryBuilder:
    def __init__(self, model_class: Type[Model]) -> None: ...
    def distinct(self) -> QueryBuilder: ...
    def select(self, *columns: Selectable) -> QueryBuilder: ...
    def count(self, column: str = "*", alias: Optional[str] = None) -> QueryBuilder: ...
    def sum(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def avg(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def min(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def max(self, column: str, alias: Optional[str] = None) -> QueryBuilder: ...
    def select_window(
        self,
        function_name: str,
        alias: str,
        partition_by: Optional[List[str]] = None,
        order_by: Optional[List[str]] = None,
    ) -> QueryBuilder: ...
    def select_case(
        self,
        alias: str,
        else_result: CaseResult,
        when_clauses: List[Tuple[str, CaseResult]],
    ) -> QueryBuilder: ...
    def from_(
        self, table: Union[QueryBuilder, str], alias: Optional[str] = None
    ) -> QueryBuilder: ...
    def with_(self, table_alias: str, subquery: QueryBuilder) -> QueryBuilder: ...
    def groupBy(self, *columns: str) -> QueryBuilder: ...
    @staticmethod
    def raw(sql: str) -> Expression: ...
    def __str__(self) -> str: ...
    def limit(self, value: int) -> QueryBuilder: ...
    def top(self, value: int) -> QueryBuilder: ...
    def union(self, *queries: QueryBuilder, all: bool = False) -> QueryBuilder: ...
    def unionAll(self, *queries: QueryBuilder) -> QueryBuilder: ...
    def offset(self, value: int) -> QueryBuilder: ...

    # Join methods
    def join(
        self,
        table: Union[str, Type[Model]],
        on: Union[str, Callable[[JoinClauseBuilder], None]],
        operator: Optional[str] = None,
        to: Optional[str] = None,
    ) -> QueryBuilder: ...
    def innerJoin(
        self,
        table: Union[str, Type[Model]],
        on: Union[str, Callable[[JoinClauseBuilder], None]],
        operator: Optional[str] = None,
        to: Optional[str] = None,
    ) -> QueryBuilder: ...
    def leftJoin(
        self,
        table: Union[str, Type[Model]],
        on: Union[str, Callable[[JoinClauseBuilder], None]],
        operator: Optional[str] = None,
        to: Optional[str] = None,
    ) -> QueryBuilder: ...
    def rightJoin(
        self,
        table: Union[str, Type[Model]],
        on: Union[str, Callable[[JoinClauseBuilder], None]],
        operator: Optional[str] = None,
        to: Optional[str] = None,
    ) -> QueryBuilder: ...
    def crossJoin(self, table: Union[str, Type[Model]]) -> QueryBuilder: ...
    def joinRelated(
        self, relation_name: str, join_type: str = "inner"
    ) -> QueryBuilder: ...
    def innerJoinRelated(self, relation_name: str) -> QueryBuilder: ...
    def leftJoinRelated(self, relation_name: str) -> QueryBuilder: ...
    def rightJoinRelated(self, relation_name: str) -> QueryBuilder: ...

    # Order By methods
    def orderBy(self, column: str, direction: str = "ASC") -> QueryBuilder: ...

    # Where methods
    @overload
    def where(
        self, column_or_callable: Callable[[WhereClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def where(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    @overload
    def andWhere(
        self, column_or_callable: Callable[[WhereClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def andWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    @overload
    def orWhere(
        self, column_or_callable: Callable[[WhereClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def orWhere(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    def whereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orWhereIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def whereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orWhereNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def whereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orWhereBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def whereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orWhereNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def whereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andWhereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orWhereExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def whereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andWhereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orWhereNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def whereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andWhereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orWhereLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def whereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andWhereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orWhereILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def whereNull(self, col: str) -> QueryBuilder: ...
    def andWhereNull(self, col: str) -> QueryBuilder: ...
    def orWhereNull(self, col: str) -> QueryBuilder: ...
    def whereNotNull(self, col: str) -> QueryBuilder: ...
    def andWhereNotNull(self, col: str) -> QueryBuilder: ...
    def orWhereNotNull(self, col: str) -> QueryBuilder: ...

    # Having methods
    @overload
    def having(
        self, column_or_callable: Callable[[HavingClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def having(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    @overload
    def andHaving(
        self, column_or_callable: Callable[[HavingClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def andHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    @overload
    def orHaving(
        self, column_or_callable: Callable[[HavingClauseBuilder], None]
    ) -> QueryBuilder: ...
    @overload
    def orHaving(
        self,
        column_or_callable: str,
        op: str,
        val: Union[Expression, DbReturnValue],
    ) -> QueryBuilder: ...
    def havingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orHavingIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def havingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def andHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def orHavingNotIn(
        self, col: str, vals: Union[List[DbReturnValue], QueryResolvable]
    ) -> QueryBuilder: ...
    def havingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orHavingBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def havingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def andHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def orHavingNotBetween(
        self, col: str, val1: DbReturnValue, val2: DbReturnValue
    ) -> QueryBuilder: ...
    def havingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andHavingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orHavingExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def havingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def andHavingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def orHavingNotExists(self, query: QueryResolvable) -> QueryBuilder: ...
    def havingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andHavingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orHavingLike(self, col: str, pattern: str) -> QueryBuilder: ...
    def havingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def andHavingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def orHavingILike(self, col: str, pattern: str) -> QueryBuilder: ...
    def havingNull(self, col: str) -> QueryBuilder: ...
    def andHavingNull(self, col: str) -> QueryBuilder: ...
    def orHavingNull(self, col: str) -> QueryBuilder: ...
    def havingNotNull(self, col: str) -> QueryBuilder: ...
    def andHavingNotNull(self, col: str) -> QueryBuilder: ...
    def orHavingNotNull(self, col: str) -> QueryBuilder: ...
