from typing import TYPE_CHECKING, Optional

from .base import Compiler

if TYPE_CHECKING:
    from sustained.schema import ColumnDef


class PostgresCompiler(Compiler):
    def quote_identifier(self, identifier: str) -> str:
        # A double quote inside the name doubles, so a name can never end
        # the quoted span early.
        return '"{}"'.format(identifier.replace('"', '""'))

    def stores_column_comments(self) -> bool:
        return True

    def compile_set_column_comment(
        self,
        table_sql: str,
        column_name: str,
        comment: Optional[str],
        column: Optional["ColumnDef"] = None,
    ) -> "list[str]":
        column_sql = self.quote_identifier(column_name)
        value = "NULL" if comment is None else self.format_value(comment)
        return [f"COMMENT ON COLUMN {table_sql}.{column_sql} IS {value}"]

    def placeholder(self) -> str:
        # The %s style used by psycopg and psycopg2.
        return "%s"

    def compile_like(self, column_sql: str, pattern_sql: str, operator: str) -> str:
        # Postgres supports ILIKE natively.
        return f"{column_sql} {operator} {pattern_sql}"

    def parenthesized_set_members(self) -> bool:
        return True

    _TYPE_MAP = {**Compiler._TYPE_MAP, "JSON": "JSONB", "BINARY": "BYTEA"}

    def compile_identity(self) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"

    def enum_strategy(self) -> str:
        return "native"

    def compile_create_enum_type(self, name: str, values: "list[str]") -> str:
        values_sql = ", ".join(self.format_value(v) for v in values)
        return f"CREATE TYPE {self.quote_identifier(name)} AS ENUM ({values_sql})"

    def compile_drop_enum_type(self, name: str, if_exists: bool = False) -> str:
        exists_sql = "IF EXISTS " if if_exists else ""
        return f"DROP TYPE {exists_sql}{self.quote_identifier(name)}"

    def compile_add_enum_value(self, name: str, value: str) -> str:
        # Runs inside a transaction from Postgres 12 on, so a rehearsal
        # can roll it back. There is no DROP VALUE to reverse it with.
        return (
            f"ALTER TYPE {self.quote_identifier(name)} "
            f"ADD VALUE {self.format_value(value)}"
        )

    def compile_distinct_on(self, columns_sql: "list[str]") -> str:
        return f"DISTINCT ON ({', '.join(columns_sql)})"

    def supports_alter_column(self) -> bool:
        return True

    def compile_alter_column_type(
        self,
        table_sql: str,
        column_name: str,
        type_sql: str,
        using: "str | None" = None,
    ) -> "list[str]":
        column_sql = self.quote_identifier(column_name)
        statement = f"ALTER TABLE {table_sql} ALTER COLUMN {column_sql} TYPE {type_sql}"
        if using:
            statement += f" USING {using}"
        return [statement]

    def compile_alter_column_nullability(
        self,
        table_sql: str,
        column_name: str,
        type_sql: str,
        nullable: bool,
    ) -> "list[str]":
        column_sql = self.quote_identifier(column_name)
        action = "DROP NOT NULL" if nullable else "SET NOT NULL"
        return [f"ALTER TABLE {table_sql} ALTER COLUMN {column_sql} {action}"]

    def compile_locking(self, skip_locked: bool, nowait: bool) -> str:
        clause = "FOR UPDATE"
        if skip_locked:
            clause += " SKIP LOCKED"
        elif nowait:
            clause += " NOWAIT"
        return clause

    def quote_fully_qualified_identifier(self, identifier: str) -> str:
        return ".".join([self.quote_identifier(part) for part in identifier.split(".")])

    def migration_lock_sql(self, name: str) -> "list[str]":
        # Session-scoped and reentrant, so a sync() that calls up() locks
        # and unlocks in balanced pairs. Released on disconnect.
        return [f"SELECT pg_advisory_lock(hashtext({self.format_value(name)}))"]

    def migration_unlock_sql(self, name: str) -> "list[str]":
        return [f"SELECT pg_advisory_unlock(hashtext({self.format_value(name)}))"]
