from .base import Compiler


class PostgresCompiler(Compiler):
    def quote_identifier(self, identifier: str) -> str:
        return f'"{identifier}"'

    def placeholder(self) -> str:
        # The %s style used by psycopg and psycopg2.
        return "%s"

    def compile_like(self, column_sql: str, pattern_sql: str, operator: str) -> str:
        # Postgres supports ILIKE natively.
        return f"{column_sql} {operator} {pattern_sql}"

    _TYPE_MAP = {**Compiler._TYPE_MAP, "JSON": "JSONB"}

    def compile_identity(self) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"

    def compile_distinct_on(self, columns_sql: "list[str]") -> str:
        return f"DISTINCT ON ({', '.join(columns_sql)})"

    def compile_locking(self, skip_locked: bool, nowait: bool) -> str:
        clause = "FOR UPDATE"
        if skip_locked:
            clause += " SKIP LOCKED"
        elif nowait:
            clause += " NOWAIT"
        return clause

    def quote_fully_qualified_identifier(self, identifier: str) -> str:
        return ".".join([self.quote_identifier(part) for part in identifier.split(".")])
