from typing import Optional

from .base import Compiler


class PostgresCompiler(Compiler):
    def quote_identifier(self, identifier: str) -> str:
        return f'"{identifier}"'

    def placeholder(self) -> str:
        # The %s style used by psycopg and psycopg2.
        return "%s"

    def compile_like(self, column_sql: str, pattern_sql: str, operator: str) -> str:
        # Postgres supports ILIKE natively.
        return f"{column_sql} {operator} {pattern_sql}"

    _TYPE_MAP = {**Compiler._TYPE_MAP, "JSON": "JSONB"}

    def compile_identity(self) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"

    def compile_distinct_on(self, columns_sql: "list[str]") -> str:
        return f"DISTINCT ON ({', '.join(columns_sql)})"

    def supports_alter_column(self) -> bool:
        return True

    def compile_alter_column_type(
        self,
        table_sql: str,
        column_name: str,
        type_sql: str,
        using: "str | None" = None,
    ) -> "list[str]":
        column_sql = self.quote_identifier(column_name)
        statement = f"ALTER TABLE {table_sql} ALTER COLUMN {column_sql} TYPE {type_sql}"
        if using:
            statement += f" USING {using}"
        return [statement]

    def compile_alter_column_nullability(
        self,
        table_sql: str,
        column_name: str,
        type_sql: str,
        nullable: bool,
    ) -> "list[str]":
        column_sql = self.quote_identifier(column_name)
        action = "DROP NOT NULL" if nullable else "SET NOT NULL"
        return [f"ALTER TABLE {table_sql} ALTER COLUMN {column_sql} {action}"]

    def compile_locking(self, skip_locked: bool, nowait: bool) -> str:
        clause = "FOR UPDATE"
        if skip_locked:
            clause += " SKIP LOCKED"
        elif nowait:
            clause += " NOWAIT"
        return clause

    def quote_fully_qualified_identifier(self, identifier: str) -> str:
        return ".".join([self.quote_identifier(part) for part in identifier.split(".")])

    def begin_transaction_sql(self) -> Optional[str]:
        # psycopg opens a transaction on the first statement of a block, so
        # an explicit BEGIN would land inside one and warn.
        return None

    def migration_lock_sql(self, name: str) -> "list[str]":
        # Session-scoped and reentrant, so a sync() that calls up() locks
        # and unlocks in balanced pairs. Released on disconnect.
        return [f"SELECT pg_advisory_lock(hashtext({self.format_value(name)}))"]

    def migration_unlock_sql(self, name: str) -> "list[str]":
        return [f"SELECT pg_advisory_unlock(hashtext({self.format_value(name)}))"]
