"""
Reading a live schema, and comparing two reads.

introspect_schema() and async_introspect_schema() report the tables,
columns, primary keys, unique constraints, foreign keys, defaults,
indexes, check constraints, column comments, and enum types a database
currently holds.
Both drive the same generator-based plan, so one dialect's reading code
serves a blocking connection and an async adapter alike.

diff_snapshots() compares two such reads. A rehearsal uses it to check
that the down steps put the schema back where it started.

The package keeps one module per dialect's plan. `model` holds what a
read reports, `normalize` the spelling reductions a diff compares on,
`scope` the schema filters the catalog reads share, `runner` the loops
that drive a plan, and `compare` diff_snapshots(). Every name, private
ones included, stays importable from here, where callers have always
found them.
"""

from __future__ import annotations

from sustained.introspect.compare import (
    _column_shape,
    _describe_column,
    diff_snapshots,
)
from sustained.introspect.duckdb import (
    _DUCKDB_IDENTIFIER_RE,
    _DUCKDB_INDEX_PART_RE,
    _DUCKDB_QUOTED_COLUMN_RE,
    _duckdb_index_column,
    _duckdb_index_columns,
    _duckdb_plan,
    _replace_duckdb_constraints,
)
from sustained.introspect.information_schema import (
    _LENGTH_TYPES,
    _MYSQL_ON_UPDATE_RE,
    _PRECISION_TYPES,
    _SYSTEM_SCHEMAS,
    ANSI_CATALOG,
    ATHENA_CATALOG,
    DUCKDB_CATALOG,
    MSSQL_CATALOG,
    MYSQL_CATALOG,
    PRESTO_CATALOG,
    Catalog,
    _catalog_filter,
    _information_schema_plan,
    _merge_plain_indexes,
    _replace_foreign_keys,
    _sized_type,
)
from sustained.introspect.model import (
    _NO_CHECKS,
    _NO_FOREIGN_KEYS,
    _NO_INDEXES,
    IntrospectedColumn,
    IntrospectedForeignKey,
    IntrospectedIndex,
    IntrospectedTable,
    SchemaPlan,
    SchemaRecorder,
    Snapshot,
)
from sustained.introspect.mssql import (
    _mssql_plan,
)
from sustained.introspect.mysql import (
    _JSON_VALID_RE,
    _mysql_plan,
    _recover_mariadb_json,
)
from sustained.introspect.normalize import (
    _CAST_RE,
    _LONE_PARENS_RE,
    _MYSQL_BARE_DEFAULT_TYPES_RE,
    _MYSQL_ENUM_RE,
    _MYSQL_ENUM_VALUE_RE,
    _MYSQL_NOW_RE,
    _MYSQL_TIME_TYPES_RE,
    _OPERATOR_SPACING_RE,
    _QUOTED_IDENTIFIER_RE,
    _SEQUENCE_DEFAULT_RE,
    _SQL_LITERAL_RE,
    _TYPE_PARAMS_RE,
    _TYPE_SYNONYMS,
    _balanced_paren_body,
    _outside_literals,
    _unquote_identifiers,
    is_sequence_default,
    mysql_default_sql,
    normalize_check,
    normalize_default,
    normalize_type,
    parse_inline_enum,
    type_params,
)
from sustained.introspect.postgres import (
    _PG_FK_ACTIONS,
    _pg_fk_action,
    _postgres_column_type,
    _postgres_plan,
)
from sustained.introspect.runner import (
    _READ_SAVEPOINT,
    _dooms_transaction,
    _finished,
    _schema_plan,
    async_introspect_schema,
    introspect_schema,
)
from sustained.introspect.scope import (
    _declared_schema,
    _is_generated_not_null_check,
    _one_schema_per_table,
    _row_text,
    _schema_literal,
    _schema_predicate,
    _scoped_filter,
)
from sustained.introspect.sqlite import (
    _SQLITE_CHECK_RE,
    _SQLITE_CHECK_START_RE,
    _SQLITE_COLLATE_RE,
    _SQLITE_FK_NAME_RE,
    _SQLITE_NAME,
    _SQLITE_NAMED_BEFORE_RE,
    _SQLITE_QUOTES,
    _SQLITE_TABLE_CONSTRAINT_RE,
    _sqlite_collations,
    _sqlite_column_name,
    _sqlite_fk_names,
    _sqlite_plan,
    _sqlite_quote,
    _sqlite_table_checks,
    _sqlite_table_parts,
    _sqlite_unnamed_checks,
    _sqlite_unquote,
    _strip_identifier,
    _unquoted,
)

__all__ = [
    "_balanced_paren_body",
    "_CAST_RE",
    "_catalog_filter",
    "_column_shape",
    "_declared_schema",
    "_describe_column",
    "_dooms_transaction",
    "_DUCKDB_IDENTIFIER_RE",
    "_duckdb_index_column",
    "_duckdb_index_columns",
    "_DUCKDB_INDEX_PART_RE",
    "_duckdb_plan",
    "_DUCKDB_QUOTED_COLUMN_RE",
    "_finished",
    "_information_schema_plan",
    "_is_generated_not_null_check",
    "_JSON_VALID_RE",
    "_LENGTH_TYPES",
    "_LONE_PARENS_RE",
    "_merge_plain_indexes",
    "_mssql_plan",
    "_MYSQL_BARE_DEFAULT_TYPES_RE",
    "_MYSQL_ENUM_RE",
    "_MYSQL_ENUM_VALUE_RE",
    "_MYSQL_NOW_RE",
    "_MYSQL_ON_UPDATE_RE",
    "_mysql_plan",
    "_MYSQL_TIME_TYPES_RE",
    "_NO_CHECKS",
    "_NO_FOREIGN_KEYS",
    "_NO_INDEXES",
    "_one_schema_per_table",
    "_OPERATOR_SPACING_RE",
    "_outside_literals",
    "_pg_fk_action",
    "_PG_FK_ACTIONS",
    "_postgres_column_type",
    "_postgres_plan",
    "_PRECISION_TYPES",
    "_QUOTED_IDENTIFIER_RE",
    "_READ_SAVEPOINT",
    "_recover_mariadb_json",
    "_replace_duckdb_constraints",
    "_replace_foreign_keys",
    "_row_text",
    "_schema_literal",
    "_schema_plan",
    "_schema_predicate",
    "_scoped_filter",
    "_SEQUENCE_DEFAULT_RE",
    "_sized_type",
    "_SQL_LITERAL_RE",
    "_SQLITE_CHECK_RE",
    "_SQLITE_CHECK_START_RE",
    "_SQLITE_COLLATE_RE",
    "_sqlite_collations",
    "_sqlite_column_name",
    "_SQLITE_FK_NAME_RE",
    "_sqlite_fk_names",
    "_SQLITE_NAME",
    "_SQLITE_NAMED_BEFORE_RE",
    "_sqlite_plan",
    "_sqlite_quote",
    "_SQLITE_QUOTES",
    "_sqlite_table_checks",
    "_SQLITE_TABLE_CONSTRAINT_RE",
    "_sqlite_table_parts",
    "_sqlite_unnamed_checks",
    "_sqlite_unquote",
    "_strip_identifier",
    "_SYSTEM_SCHEMAS",
    "_TYPE_PARAMS_RE",
    "_TYPE_SYNONYMS",
    "_unquote_identifiers",
    "_unquoted",
    "ANSI_CATALOG",
    "async_introspect_schema",
    "ATHENA_CATALOG",
    "Catalog",
    "diff_snapshots",
    "DUCKDB_CATALOG",
    "introspect_schema",
    "IntrospectedColumn",
    "IntrospectedForeignKey",
    "IntrospectedIndex",
    "IntrospectedTable",
    "is_sequence_default",
    "MSSQL_CATALOG",
    "MYSQL_CATALOG",
    "mysql_default_sql",
    "normalize_check",
    "normalize_default",
    "normalize_type",
    "parse_inline_enum",
    "PRESTO_CATALOG",
    "SchemaPlan",
    "SchemaRecorder",
    "Snapshot",
    "type_params",
]
